create extension if not exists pgcrypto;

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  username text not null unique,
  password_hash text not null,
  full_name text,
  mssv text,
  class_name text,
  gender text,
  phone text,
  email text,
  avatar_url text,
  role text not null default 'user',
  profile_complete integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.computers (
  id bigint generated by default as identity primary key,
  name text not null,
  room text not null,
  specs text,
  status text not null default 'available',
  created_at timestamptz not null default now(),
  unique(name, room)
);

create table if not exists public.borrow_requests (
  id bigint generated by default as identity primary key,
  computer_id bigint not null references public.computers(id) on delete cascade,
  borrower_id bigint not null references public.users(id) on delete cascade,
  reason text,
  status text not null default 'pending',
  requested_at timestamptz not null default now(),
  approved_by bigint references public.users(id),
  approved_at timestamptz,
  returned_at timestamptz
);

create index if not exists idx_computers_status on public.computers(status);
create index if not exists idx_borrow_requests_status on public.borrow_requests(status);
create index if not exists idx_borrow_requests_computer_id on public.borrow_requests(computer_id);
create index if not exists idx_borrow_requests_borrower_id on public.borrow_requests(borrower_id);

insert into public.users (username, password_hash, full_name, email, role, profile_complete)
values ('admin', '$2a$10$0r9aJYv5/4V4bE1NRU0rQe3v7d1n7JO0Nt0fD7m6kJmU7l6qkVbiS', 'System Admin', 'admin@example.com', 'admin', 1)
on conflict (username) do nothing;

insert into public.computers (name, room, specs, status)
values
  ('M01', 'C201', 'Intel i5, 16GB RAM, SSD 512GB', 'available'),
  ('M02', 'C201', 'Intel i7, 16GB RAM, SSD 512GB', 'available'),
  ('M03', 'C201', 'Intel i5, 8GB RAM, SSD 256GB', 'available'),
  ('M04', 'C201', 'Intel i7, 32GB RAM, SSD 1TB', 'available')
on conflict (name, room) do nothing;

insert into public.borrow_requests (computer_id, borrower_id, reason, status)
select c.id, u.id, 'Cần làm bài tập nhóm', 'pending'
from public.computers c
join public.users u on u.username = 'admin'
where c.name = 'M01'
on conflict do nothing;
